name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If useful, add screenshots or a screen recording to help explain your problem.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction & Sample Text
      description: > 
        Include sample text and mark clearly how the text looks before and after the operation 
        and what you expected the text to look like. Include the cursor positions.
      placeholder: |
        before: 
        after: 
        expected: 
        *include cursor positions*
    validations:
      required: true
  - type: textarea
    id: version-info
    attributes:
      label: neovim version
      render: Text
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Make sure you have done the following
      options:
        - label: I have updated to the latest version of the plugin.
          required: true
